# Generated by Django 4.0.3 on 2022-09-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_rename_automobilevo_carvo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvo',
            name='import_href',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
